// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlozxdxkixgkswnlncoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpsb3p4ZHhraXhna3N3bmxuY29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4Mzk0ODEsImV4cCI6MjA3ODQxNTQ4MX0.YekCu2RTZdPCVeRdrGXu6pOUVoc_P_LKOwG_lNVC2RM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});